language: node_js
node_js:
  - "10.16"
before_install:
  - COPYLOC=`pwd`
  - echo $COPYLOC
  - cd ~ && git clone https://github.com/bhashkarsharma/content && cd content
  - pwd
  - POSTPATH="$COPYLOC/src/content/posts"
  - mkdir -p $POSTPATH
  - cp -r posts/* $POSTPATH
  - GALLERYPATH="$COPYLOC/src/content/gallery/photos"
  - mkdir -p $GALLERYPATH
  - cp -r gallery/photos/* $GALLERYPATH
  - cp gallery/gallery.json $COPYLOC/src/content/json/gallery.json
  - cd $COPYLOC
install:
  - pip install --user awscli
  - npm install
script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: $BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: public
  detect_encoding: true
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
